#!/bin/bash
if [[ -L $0 ]]; then
    export SCRIPT_DIR=$(dirname $(readlink $0))
else
    export SCRIPT_DIR=$(dirname $(readlink -f $0))
fi

docker run --rm -ti \
    --name trainer \
    -e AWS_ACCESS_KEY_ID \
    -e AWS_CONFIG_FILE \
    -e AWS_DEFAULT_PROFILE \
    -e AWS_DEFAULT_REGION \
    -e AWS_DEFAULT_OUTPUT \
    -e AWS_SECRET_ACCESS_KEY \
    -e AWS_SESSION_TOKEN \
    -e USER \
    -e SSH_AUTH_SOCK \
    -e SCRIPT_DIR=/trainer-tools \
    -e LOCAL_PATH=$SCRIPT_DIR \
    -v `pwd`:/workdir \
    -v $SCRIPT_DIR:/trainer-tools/ \
    -v $(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) \
    -w /workdir \
    --entrypoint "/trainer-tools/scripts/trainer-cli" \
    soulshake/trainer-tools "$@"
